In [1]:
rdd = sc.parallelize([1,2,3,4,5,6,7] , 3)

In [2]:
rdd.glom().collect()

In [3]:
rdd.map(lambda x : x+2).map(lambda x : x*5).collect()

In [4]:
rdd1 = sc.textFile("/FileStore/tables/Baby_Names__Beginning_2007.csv")

In [5]:
rdd1.first()

In [6]:
rdd1.take(5)

In [7]:
rdd1.map(lambda x : len(x)).take(5)

In [8]:
rdd = sc.parallelize(['hello' , 'world' , 'spark' , 'hello'])

In [9]:
rdd.map(lambda x : (x , 1)).reduceByKey(lambda x,y : x+y).collect()

In [10]:
rdd1 = sc.parallelize([1,2,3,4,5,6,7,8,9])
rdd2 = sc.parallelize([1,2,3,4,5,6,7,8,9])

In [11]:
rdd1.union(rdd2).reduce(lambda x : x)

In [12]:
seqOp = (lambda x , y : (x[0] +y , x[1] + 1))
combOp = (lambda x , y: (x[0] + y[0] , x[1] + y[1]))

In [13]:
print sc.parallelize([('hello' , 1) , ('hello' , 2) , ('good' , 1) , ('food' , 1)]).aggregateByKey((0,0), seqOp , combOp).collect()

In [14]:
rdd = sc.parallelize([(('abc' , 'def') , 11) , (('efg' , 'hij') , 22) , (('abc' , 'def') , 14) , (('efg' , 'hij') , 13)])

In [15]:
def first(x):
  print 'in first'
  return x

def second(x , y):
    print 'second'
    return x+y
  
def third(x,y):
  print 'in third'
  return x+y


rdd.combineByKey(first , second , third).collect()

In [16]:
rdd.getNumPartitions()

In [17]:
titanicData = spark.read.csv('/FileStore/tables/titanic_train-ac800.csv' , header = True , inferSchema=True);

In [18]:
titanicData.show()

In [19]:
titanicData.agg({'Age' : 'max'}).collect()

In [20]:
display(titanicData.describe());

In [21]:
print titanicData.filter(titanicData.Survived == 0).filter(titanicData.Age < 18).count();

In [22]:
addedAgeTitanic = titanicData.withColumn('newAge' , titanicData.Age + 5).show();

In [23]:
titanicData.select('Name' , 'Age' , (titanicData.Age < 18)).show();

In [24]:
from pyspark.sql import functions as F
titanicData.select(titanicData.Name , F.when(titanicData.Age > 18 , True).otherwise(False).alias('Kid')).show();